### ISSUE TITLE
你们fork后有什么添加修改的都可以pull，大家都是新手，一起交流

### ISSUE THREAD

**Issue by sword-jin** [RryLee/StuGradeWithLaravel5#1]
也可以让后来的新人们避免更多的坑，更好的上手
PS：最近要课设，可能没什么时间，跟多说一下，添加队友什么的也是可以的！
祝：编码快乐！

**Comment by sword-jin** [comment]
@YidaChen  都快忘记这个地方了，那个时候不知道是什么原因导致无法初始化grade，现在貌似是可以的，不需要调整id类型吧，直接int

**Comment by YidaChen** [comment]
我尝试把id设很大的话，插入后id会变成4294967295
